spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/meetmind_db
        username: meetmind
        password: meetmind
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate: 
            ddl-auto: update
app:
    jwt-secret: whrjbfwhrfihrihfri
    jwt-expiration-ms: 3600000