spring:
    application:
        name: auth-service
    lifecycle:
        timeout-per-shutdown-phase: 30s

    profiles:
        active : dev
    cache:
        type: redis
    data:
        redis:
            host: localhost
            port: 6379


server:
    port: 8081
    compression:
        enabled: true
        mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
        min-response-size: 1024
    shutdown: graceful
        

