services:

  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - meetmind-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - meetmind-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/meetmind_db
    depends_on:
      - discovery-service
      - database
    networks:
      - meetmind-network

  upload-service:
    build:
      context: ./upload-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/meetmind_db
    depends_on:
      - discovery-service
      - database
    networks:
      - meetmind-network

  ai_transcrition-service:
    build:
      context: ./ai_transcrition-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - meetmind-network

  ai_summarization-service:
    build:
      context: ./ai_summarization-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - meetmind-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - meetmind-network

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: meetmind
      POSTGRES_PASSWORD: meetmind
      POSTGRES_DB: meetmind_db
    ports:
      - "5432:5432"
    networks:
      - meetmind-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - meetmind-network

networks:
  meetmind-network:
    driver: bridge

volumes:
  postgres_data:
