spring:
  application:
    name: gateway
  config:
    import:
      - "classpath:/routes.yml"

resilience4j:
  circuitbreaker:
    instances:
      default:
        register-health-indicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret-key: your-secret-key
  expiration: 3600 # in seconds
